### ISSUE TITLE
Data sets that are interesting for journalists

### ISSUE THREAD

**Issue by HeidiSeibold** [school-of-data/r-consortium-proposal#5]
Please recommend us data sets that you think could be useful in an R data journalism course.

Best would be if you already did something in R with that data set so we can reuse the code or if you'd know what could be a good story to write with the info from the data set.

**Comment by karillith** [comment]
Hi there! I'd like to contribute to this. How can I do so? Should I submit a pull request and create a new directory that maybe contains a markdown to different links and stories to tell? Thanks :)

**Comment by HeidiSeibold** [comment]
Hi @karillith your proposed way to do this sounds great. Ask as many questions as you like along the way, e.g. on gitter: https://gitter.im/school-of-data/r-consortium-proposal

Are you a journalist? Do you know R?

**Comment by karillith** [comment]
@HeidiSeibold I've used a bit of R on and off during my MA in Linguistics, but I'm not a journalist. As someone who studied a "soft science" and didn't have a lot of exposure to data sets, I can definitely relate to wanting to build a great technical resource like this. I'll do a little digging today and this weekend and see if I can submit a pull soon!

**Comment by HeidiSeibold** [comment]
Thanks @karillith for your help :cake:. If you want to get involved further, we'd love to hear from you. Find out how you can help [here](https://github.com/school-of-data/r-consortium-proposal/blob/master/CONTRIBUTING.md).
