### ISSUE TITLE
Go through the intro lesson and let us know what you think

### ISSUE THREAD

**Issue by HeidiSeibold** [school-of-data/r-consortium-proposal#7]
The [intro lesson](https://github.com/school-of-data/r-consortium-proposal/blob/master/material/lessons/Introduction.Rmd) is supposed to convince data journalists that R is a great tool for them.

It needs to be really good and clear for someone who never has used R before.

Since this lesson is not in an interactive website yet where you can type your code there, it would be good if you install R and RStudio. This way you can try everything and see if it works for you. See for example http://www.ics.uci.edu/~jutts/110/InstallingRandRStudio.pdf

**Comment by huyvohcmc** [comment]
How can I resolve this issue for hacktoberfest?

**Comment by HeidiSeibold** [comment]
There are two ways:

1. Add your comments to this issue
2. Create a pull request for the intro lesson where you improve parts

Does that help? Thanks for getting in touch :cake:

**Comment by niketmishra** [comment]
The intro lesson was good.I am quite sure R will completely replace the spreadsheets very soon.
You can also explain how data is imported in R language in that lesson.

**Comment by miaket** [comment]
Nice. Can i still help you guys out with that?  :)
Are you planning on making it a website in the future? That intro would fit in it very well.

**Comment by puripant** [comment]
Good introduction to R! I have just gone through the whole introduction and found it helpful although slightly hard despite working code for all sections. Anyway, some `ggplot` commands run really slow and there should be some warnings about that and probably some result images to confirm to the learner that they have put in the right commands. (The last four commands took a few minutes to complete. My computer is MacBook Pro 2015.) I can work on this if it's okay.

Also, if all `install(...)` and `library(...)` commands are in the beginning, it may save some time and make the whole tutorial go more smoothly. Suggesting the UI to install and load libraries in RStudio (Packages tab/pane then Install) can be more newbie-friendly as well.

**Comment by HeidiSeibold** [comment]
Wow so much helpers! Thanks guys!

Yes, we need more help @miaket. You can also check out the data recipes (see #8) if you prefer.

>Are you planning on making it a website in the future? That intro would fit in it very well.

Yes, in the end it is supposed to be an interactive website (using the learnr package to make it interactive). If you have experience with these things, help is very welcome on that side, too. Email me (heidi@schoolofdata.ch) if you'd like to get involved on that end :smile:  

@niketmishra thanks for your feedback :+1: . Is there anything you would do differently?

@puripant very good points :+1: . If you want, you can create a pull request with your suggestions implemented.

**Comment by HeidiSeibold** [comment]
We have a gitter chat now, so you can also message there https://gitter.im/school-of-data/r-consortium-proposal

**Comment by HeidiSeibold** [comment]
Also we are thinking about how to improve testing of material (like what you are doing). Maybe you have thoughts on that (see #13)

**Comment by HeidiSeibold** [comment]
Closing this now.

If you want to keep helping with this, please be our first guided beta testers for the introduction material. It has changed quite a bit since you tested it. 

Here is how you can do it: https://github.com/school-of-data/r-consortium-proposal/blob/master/CONTRIBUTING.md#beta-testing

Would love to hear from you again. Thanks all for helping!
