### ISSUE TITLE
Go through data recipes and let us know what you think

### ISSUE THREAD

**Issue by HeidiSeibold** [school-of-data/r-consortium-proposal#8]
Look at one of our first recipes we have started.

- The following data recipes
    + [Switzerland dual use goods](https://github.com/school-of-data/r-consortium-proposal/blob/master/material/lessons/switzerland-dual-use/recipe_switzerland-dual-use.Rmd)
     + [WIP - Visualisation of polls results during presidential election in France](https://github.com/school-of-data/r-consortium-proposal/blob/master/material/lessons/polls.Rmd)

The first one is a bit more advanced than the second one. Go through the code and let us know if it is clear and easy to understand. In the end all data recipes are supposed to adhere to a standard. This is why we created a [template](https://github.com/school-of-data/r-consortium-proposal/tree/master/r-package/inst/tutorials/en-recipe-template). You can also check it out in R via
```
devtools::install_github("school-of-data/r-consortium-proposal", 
                         subdir="r-package")
learnr::run_tutorial("en-recipe-template", package = "ddj")
```

You can solve this issue in two different ways:

1.    Add your comments to this issue
2.   Create a pull request for the recipes where you improve parts

**Comment by puripant** [comment]
I have some problems following this data recipe: [WIP - Visualisation of polls results during presidential election in France](https://github.com/school-of-data/r-consortium-proposal/blob/master/material/lessons/polls.Rmd). First, there is only code and no description. Also, all comments are in French. I could work on this if I could follow through the end and understand the objectives of the data recipe but I encountered an error at this line:

`colnames(polls_round1) <- c("Poll source","Fieldwork date", "Sample size", "Abstention", "Arthaud", "Poutou", "Mélenchon", "Hamon", "Macron", "Lassalle","Fillon", "Dupont-Aignan", "Asselineau","Le Pen", "Cheminade") #enlever les partis des noms de colonnes`

The error was:

```
Error in names(x) <- value : 
  'names' attribute [15] must be the same length as the vector [6]
```

**Comment by HeidiSeibold** [comment]
@samgoeta can you help?

**Comment by HeidiSeibold** [comment]
@puripant this is being updated a lot currently. We are officially starting with beta testing in January. You can find out [here](https://github.com/school-of-data/r-consortium-proposal/blob/master/CONTRIBUTING.md#beta-testing) which parts are ready for testing. 

Thanks :cake:
